project:
  type: website

website:
  title: GitHub template for FAIR and open research data
  favicon: _extensions/sgb-theme/favicon.png
  open-graph: true
  twitter-card: true
  site-url: https://maehr.github.io/open-research-data-template/
  repo-url: https://github.com/maehr/open-research-data-template/
  issue-url: https://github.com/maehr/open-research-data-template/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: _extensions/sgb-theme/assets/img/logo.svg
    logo-alt: 'Stadt.Geschichte.Basel Logo'
    title: open-research-data-template
    tool-collapse: true
    tools:
      - icon: github
        url: https://github.com/maehr/open-research-data-template/
    left:
      - text: Readme
        href: index.qmd

  sidebar:
    contents:
      - section: open-research-data-template
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format:
  sgb-theme-html:
    toc: true
    code-copy: true
    code-overflow: wrap

freeze: true

editor: visual
