contact_links:
  - name: Are you looking for documentation on iconclass-classification?
    url: https://Stadt-Geschichte-Basel.github.io/iconclass-classification
    about: Please see the documentation for iconclass-classification on its GitHub Pages page.
  - name: Do you want to discuss iconclass-classification with the community?
    url: https://github.com/Stadt-Geschichte-Basel/iconclass-classification/discussions
    about: Please see the discussions page for iconclass-classification.
blank_issues_enabled: true
